version: '3.4'

services:

  # FRONTEND
  frontend:
    build:
      context: ./burgercraft-app_frontend
    image: burgercraft_app.frontend
    container_name: burgercraft_app.frontend
    ports:
      - ${APP_PORT}:80
    networks:
      - app_network

  # BACKEND
  backend:
    build:
      context: ./burgercraft-app_backend
    image: burgercraft_app.backend
    container_name: burgercraft_app.backend
    ports:
      - ${API_PORT}:3000
    networks:
      - app_network
    depends_on:
      - mysql

  # DATABASE
  mysql:
    build:
      context: ./mysql
    image: burgercraft_app.mysql
    container_name: burgercraft_app.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - app_network

  # WEB SERVER
  nginx:
    build:
      context: ./nginx
    image: burgercraft_app.nginx
    container_name: burgercraft_app.nginx
    ports:
      - ${NGINX_PORT}:80
    networks:
      - app_network
    depends_on:
      - frontend
      - backend

networks:
  app_network:
    driver: bridge